spring.application.name=ecom
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
cors.allowed=http://localhost:5173,http://127.0.0.1:5173
#SMTP MAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=xxxxxxxxxxxxxxxxxxx
spring.mail.password=xxxxxxxxxxxxxxxxxxx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#SENDGRID (API for mail)
sendgrid.api.key=xxxxxxxxxxxxxxxxxxxx
sendgrid.verified.email=xxxxxxxxxxxxxxxxxxxxxxxxx
#Mailgun (API for mail)
mailgun.api.key=xxxxxxxxxxxxxxxxxxxxx
mailgun.domain=xxxxxxxxxxxxxxxxxxxx
mailgun.from=xxxxxxxxxxxxxxxx
#CONFIG EMAIL PROVIDER
email.provider=sendgrid

jwt.secret = "ThisIsAVeryLongSecretKeyAtLeast32Chars123456_ThisIsAVeryLongSecretKeyAtLeast32Chars123456_ThisIsAVeryLongSecretKeyAtLeast32Chars123456"

# spring.security.user.name = root
# spring.security.user.password = root